# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/work/SCA-Core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/work/SCA-Core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/work/SCA-Core/CMakeFiles /home/pi/work/SCA-Core//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/work/SCA-Core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_ble_log

# Build rule for target.
test_ble_log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ble_log
.PHONY : test_ble_log

# fast build rule for target.
test_ble_log/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ble_log.dir/build.make CMakeFiles/test_ble_log.dir/build
.PHONY : test_ble_log/fast

#=============================================================================
# Target rules for targets named test_nfc_log

# Build rule for target.
test_nfc_log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_nfc_log
.PHONY : test_nfc_log

# fast build rule for target.
test_nfc_log/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_nfc_log.dir/build.make CMakeFiles/test_nfc_log.dir/build
.PHONY : test_nfc_log/fast

#=============================================================================
# Target rules for targets named rpi_can_router

# Build rule for target.
rpi_can_router: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rpi_can_router
.PHONY : rpi_can_router

# fast build rule for target.
rpi_can_router/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpi_can_router.dir/build.make CMakeFiles/rpi_can_router.dir/build
.PHONY : rpi_can_router/fast

tests/rpi_can_router.o: tests/rpi_can_router.cpp.o
.PHONY : tests/rpi_can_router.o

# target to build an object file
tests/rpi_can_router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpi_can_router.dir/build.make CMakeFiles/rpi_can_router.dir/tests/rpi_can_router.cpp.o
.PHONY : tests/rpi_can_router.cpp.o

tests/rpi_can_router.i: tests/rpi_can_router.cpp.i
.PHONY : tests/rpi_can_router.i

# target to preprocess a source file
tests/rpi_can_router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpi_can_router.dir/build.make CMakeFiles/rpi_can_router.dir/tests/rpi_can_router.cpp.i
.PHONY : tests/rpi_can_router.cpp.i

tests/rpi_can_router.s: tests/rpi_can_router.cpp.s
.PHONY : tests/rpi_can_router.s

# target to generate assembly for a file
tests/rpi_can_router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rpi_can_router.dir/build.make CMakeFiles/rpi_can_router.dir/tests/rpi_can_router.cpp.s
.PHONY : tests/rpi_can_router.cpp.s

tests/test_ble_log.o: tests/test_ble_log.cpp.o
.PHONY : tests/test_ble_log.o

# target to build an object file
tests/test_ble_log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ble_log.dir/build.make CMakeFiles/test_ble_log.dir/tests/test_ble_log.cpp.o
.PHONY : tests/test_ble_log.cpp.o

tests/test_ble_log.i: tests/test_ble_log.cpp.i
.PHONY : tests/test_ble_log.i

# target to preprocess a source file
tests/test_ble_log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ble_log.dir/build.make CMakeFiles/test_ble_log.dir/tests/test_ble_log.cpp.i
.PHONY : tests/test_ble_log.cpp.i

tests/test_ble_log.s: tests/test_ble_log.cpp.s
.PHONY : tests/test_ble_log.s

# target to generate assembly for a file
tests/test_ble_log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ble_log.dir/build.make CMakeFiles/test_ble_log.dir/tests/test_ble_log.cpp.s
.PHONY : tests/test_ble_log.cpp.s

tests/test_nfc_log.o: tests/test_nfc_log.cpp.o
.PHONY : tests/test_nfc_log.o

# target to build an object file
tests/test_nfc_log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_nfc_log.dir/build.make CMakeFiles/test_nfc_log.dir/tests/test_nfc_log.cpp.o
.PHONY : tests/test_nfc_log.cpp.o

tests/test_nfc_log.i: tests/test_nfc_log.cpp.i
.PHONY : tests/test_nfc_log.i

# target to preprocess a source file
tests/test_nfc_log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_nfc_log.dir/build.make CMakeFiles/test_nfc_log.dir/tests/test_nfc_log.cpp.i
.PHONY : tests/test_nfc_log.cpp.i

tests/test_nfc_log.s: tests/test_nfc_log.cpp.s
.PHONY : tests/test_nfc_log.s

# target to generate assembly for a file
tests/test_nfc_log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_nfc_log.dir/build.make CMakeFiles/test_nfc_log.dir/tests/test_nfc_log.cpp.s
.PHONY : tests/test_nfc_log.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rpi_can_router"
	@echo "... test_ble_log"
	@echo "... test_nfc_log"
	@echo "... tests/rpi_can_router.o"
	@echo "... tests/rpi_can_router.i"
	@echo "... tests/rpi_can_router.s"
	@echo "... tests/test_ble_log.o"
	@echo "... tests/test_ble_log.i"
	@echo "... tests/test_ble_log.s"
	@echo "... tests/test_nfc_log.o"
	@echo "... tests/test_nfc_log.i"
	@echo "... tests/test_nfc_log.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

