#pragma once
#include <cstdint>

// ===== 프로젝트 공통 CAN ID (11-bit) =====
enum : uint32_t {
    // DCU ↔ SCA
    PCAN_ID_DCU_RESET = 0x001,
    PCAN_ID_DCU_RESET_ACK = 0x002,

    PCAN_ID_SCA_DCU_DRIVER_EVENT = 0x003,
    PCAN_ID_DCU_SCA_DRIVE_STATUS = 0x005,

    PCAN_ID_DCU_SCA_USER_FACE_REQ = 0x101,
    PCAN_ID_SCA_TCU_USER_INFO_REQ = 0x102,
    PCAN_ID_SCA_DCU_AUTH_STATE = 0x103,
    PCAN_ID_TCU_SCA_USER_INFO = 0x104,
    PCAN_ID_TCU_SCA_USER_INFO_NFC = 0x107,
    PCAN_ID_TCU_SCA_USER_INFO_BLE_SESS = 0x108,
    PCAN_ID_TCU_SCA_USER_INFO_BLE_CHALL = 0x109,
    PCAN_ID_TCU_SCA_USER_INFO_BLE_FLAG = 0x110,

    PCAN_ID_SCA_TCU_USER_INFO_ACK = 0x111,
    PCAN_ID_SCA_DCU_AUTH_RESULT = 0x112,
    PCAN_ID_SCA_DCU_AUTH_RESULT_ADD = 0x113,

    PCAN_ID_DCU_TCU_USER_PROFILE_REQ = 0x201,
    PCAN_ID_TCU_DCU_USER_PROFILE_SEAT = 0x202,
    PCAN_ID_TCU_DCU_USER_PROFILE_MIRROR = 0x203,
    PCAN_ID_TCU_DCU_USER_PROFILE_WHEEL = 0x204,
    PCAN_ID_DCU_TCU_USER_PROFILE_ACK = 0x205,

    PCAN_ID_DCU_TCU_USER_PROFILE_SEAT_UPDATE = 0x206,
    PCAN_ID_DCU_TCU_USER_PROFILE_MIRROR_UPDATE = 0x207,
    PCAN_ID_DCU_TCU_USER_PROFILE_WHEEL_UPDATE = 0x208,
    PCAN_ID_TCU_DCU_USER_PROFILE_UPDATE_ACK = 0x209,
};

// 간단 signal packing helper
static inline uint8_t clamp8(int v) { return (v < 0) ? 0 : ((v > 255) ? 255 : v); }
